//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorWithDevice.GadgeteerApp {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The LED 7C module using socket 7 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7C led7C;
        
        /// <summary>The USB Client DP module using socket 8 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.USBClientDP usbClientDP;
        
        /// <summary>The BluetoothSmart module using socket 6 of the mainboard.</summary>
        private Gadgeteer.Modules.IngenuityMicro.BluetoothSmart bluetoothSmart;
        
        /// <summary>The Joystick module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Joystick joystick;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZCerberus Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZCerberus)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZCerberus();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.led7C = new GTM.GHIElectronics.LED7C(7);
            this.usbClientDP = new GTM.GHIElectronics.USBClientDP(8);
            this.bluetoothSmart = new GTM.IngenuityMicro.BluetoothSmart(6);
            this.joystick = new GTM.GHIElectronics.Joystick(4);
        }
    }
}
